### ISSUE TITLE
Thumbnail-Previews not working persistently

### ISSUE THREAD

**Issue by tiku01** [tiku01/oryx-editor#523]
Thumbnail pictures get generated after saving a new model and then get shown once in the overview. After that the pictures disappear.

**Comment by tiku01** [comment]
With fix https://github.com/tiku01/oryx-editor/pull/518 the previews work if only using non-encrypted connections (http on port :8080 instead of https on port :8443) ...

**Comment by tiku01** [comment]
Another thing: For a UML Class Diagram there is no preview shown at all (e.g. model/33).

**Comment by gautamsawala** [comment]
Updated the pull-request #518 with a commit that must work for encrypted connections (https://)

Now checking with UML Class Diagram preview.

**Comment by tiku01** [comment]
UML Class Diagram seems to still have problems ...

**Comment by gautamsawala** [comment]
Addressed the issue with #541

**Comment by tiku01** [comment]
After clean deployment (deleting old directories) this seems to be working correctly now, thx!
