### ISSUE TITLE
Database schema needs update of thumbnail-fix

### ISSUE THREAD

**Issue by tiku01** [tiku01/oryx-editor#536]
The fix from https://github.com/gautamsawala/oryx-editor/commit/89037989524cbf33890d61cf01a028e2a363ad69 needs to be included in the database schema for new installations! It was added with https://github.com/tiku01/oryx-editor/pull/518 ....

**Comment by gautamsawala** [comment]
The fix has been added in the db_schema for new installation with the pull #540
